# Lab01 - Getting Started

Name: Harrison Halesworth
Class: CSCI 349 - Intro to Data Mining
Section: 01 - 11am
Semester: Spring 2024
Instructors: Brian King

In [61]:
import sys
print(sys.version)

3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]


**2.** [M] Did you read the syllabus? All of it? Do you understand and agree to abide by the cheating rules? Write a 
sentence clearly indicating your commitment to not cheating.

I read the syllabus and am stating that I will be completely committed to not cheating in this course

**3.** [M] What are you hoping to get out of this course?

I am hoping to learn as much as possible about the entire pipeline of data science and engineering as to become a more well rounded computer scientist overall, as foundational knowledge and experience working with data will undoubtedly come in handy in my career.

**4.** [P] Print the Python version (available in sys package)

In [62]:
import sys
print(sys.version)

3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]


**5** [P] Create a Python list of 10000 random integers in the range 1 to 100 using the random package. Name the 
list x_list.

In [63]:
import random

# 10000 random ints between 1 and 100 using list comprehension
x_list = [random.randint(1, 100) for i in range(10000)]

**6.** [P] What is the minimum x_list? What is the max value? What is the mode?

In [64]:
from statistics import mode
print("The min of x_list is: " + str(min(x_list)))
print("The max of x_list is: " + str(max(x_list)))
print("The mode of x_list is: " + str(mode(x_list)))

The min of x_list is: 1
The max of x_list is: 100
The mode of x_list is: 10


**7.** [P] Write a function to take a list of numbers as a parameter and return the average of the list. Then, use your 
function to report the average value of x_list, printed as a float with 2 places of precision.

In [65]:
from statistics import mean
def avg_val(nums):
    return mean(nums)
    
mean = avg_val(x_list)

# https://realpython.com/python-f-strings/
print("The mean of x_list is: " + f"{mean:.2f}")

The mean of x_list is: 51.12


**8.** [P] Create a list called x_hist that represents a histogram, i.e. a distribution of the numerical data, of 
x_list. Each entry in x_hist should contain the frequency of data over a bin width of 10. So, for example,
x_hist[0] represents the frequency of numbers between 1-10, x_hist[1] is the frequency of numbers 
between 11-20, and so on. Be sure to print x_hist at the end.

In [66]:
x_hist = [0] * 10
for num in x_list:
    x_hist[(num-1)//10] += 1

print(x_hist)
print("Sum of contents of x_hist should be 10000, is: " + str(sum(x_hist)))

[1016, 975, 943, 1020, 953, 1005, 973, 999, 1025, 1091]
Sum of contents of x_hist should be 10000, is: 10000


**9.** [M] What is numpy? What are its strengths? Does it have any weaknesses?

https://numpy.org/doc/stable/user/whatisnumpy.html

numpy is a Python library that is catered to programmers dealing with data, along the entirety of the pipeline. It imports things such as matrices, masked arrays, fourier transforms and other data types and operations to allow you to analyze data without the hassle of implementing these things yourself. One of the biggest strengths of numpy is that it is fast and efficient and it is because all the code it provides is vectorized and designed to have these mathematical operations completed on it. It's weaknesses are more subjective as the struggle of use will more likely come from learning all that comes with the package and that can be said about most commonly used Pythong libraries, but one true weakness is that it is not well suited for small datasets as the overhead will not be worth it, but I doubt I will be dealing with small datasets this semester.

**10.** [P] Import the numpy package as np and print the numpy version


In [67]:
import numpy as np
print("The current version is: " + str(np.__version__))

The current version is: 1.26.3


**11.** [M] What is the primary object type in numpy? Can it store data of different types? Discuss.

https://numpy.org/doc/stable/user/whatisnumpy.html

The primary object type in numpy is the ndarray which stands for n-dimensional array, and basically serves as a matrix. You can store different types in an ndarray but they all have to be uniform throughout that respective ndarray, for instance an ndarray with ints in it must only have ints in it.

**12.** [M] Discuss the types of data available in numpy. You need not list every type. Just generalize, and discuss 
how the type system is different than the built-in types int and float in Python.

https://numpy.org/doc/stable/user/basics.types.html

There are several different types unique to the numpy library and what differentiates most of them from the built-in Python types is you can determine the precision of numerical values to be used in your ndarray via the different types. Precision of values are extremely important in data analysis you'll come to find as lowering or adding a single digit of precision can sometimes have a drastic difference (I saw this first hand in MATH343).

**13.** [P] Research how to use numpy to compute the same result as problem 8 above. (HINT: np.histogram)

In [68]:
# https://www.geeksforgeeks.org/numpy-histogram-method-in-python/#

x_hist = np.histogram(x_list, bins = [(10*i + 1) for i in range(0,11)])
print(x_hist[0])
print(x_hist[1])

[1016  975  943 1020  953 1005  973  999 1025 1091]
[  1  11  21  31  41  51  61  71  81  91 101]


**14.** [P] Create a numpy array from x_list. Reassign it as x_list. Show the contents of the first 20 entries.

In [69]:
import copy
# https://numpy.org/doc/stable/user/basics.creation.html

x_list2 = copy.deepcopy(x_list)
x_list = np.array(x_list)
print("The first 20 entries of x_list are: " + str(x_list[0:20]))

The first 20 entries of x_list are: [68  6 43 35 18 47 41 44 97 14  3 88 95  8 24 48 90 91 40  2]


**15.** [P] Redo the previous exercise, but set the data type of each value to 'float32'

In [70]:
# https://numpy.org/doc/stable/user/basics.creation.html

x_list = np.array(x_list2, dtype='float32')
print("The first 20 entries of x_list are: " + str(x_list[0:20]))

The first 20 entries of x_list are: [68.  6. 43. 35. 18. 47. 41. 44. 97. 14.  3. 88. 95.  8. 24. 48. 90. 91.
 40.  2.]


**16.** [P] Create a length 10 integer array filled with zeros

In [71]:
# https://numpy.org/doc/stable/user/basics.creation.html

arr = np.zeros(10, dtype='int')
print(arr)

[0 0 0 0 0 0 0 0 0 0]


**17.** [P] Create a float array of 3 rows and 4 columns, all initialized to one.

In [72]:
# https://numpy.org/doc/stable/user/basics.creation.html

arr = np.ones((3,4), dtype='int')
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


**18.** [P] Create an array of 20 values, evenly spaced between 1 and 3 (HINT – look at np.linspace)

In [73]:
# https://numpy.org/doc/stable/user/basics.creation.html

arr = np.linspace(1, 3, 20)
print(arr)

[1.         1.10526316 1.21052632 1.31578947 1.42105263 1.52631579
 1.63157895 1.73684211 1.84210526 1.94736842 2.05263158 2.15789474
 2.26315789 2.36842105 2.47368421 2.57894737 2.68421053 2.78947368
 2.89473684 3.        ]


**19.** [P] Set the numpy random seed to the value 12345, then create a 10 x 5 array of random integers on the 
interval [10, 50), assigned to x_mat

In [74]:
# https://numpy.org/doc/stable/user/basics.creation.html

np.random.seed(12345)
x_mat = np.random.randint(10,50,size=(10,5))
print(x_mat)

[[44 47 39 11 46]
 [47 44 39 11 24]
 [37 26 19 21 23]
 [20 27 28 48 17]
 [49 33 39 41 43]
 [37 33 46 10 13]
 [15 25 21 24 27]
 [15 44 18 15 44]
 [15 29 22 24 26]
 [37 48 34 42 15]]


**20.** [P] Use slicing to select and show the first and last row of x_mat

In [75]:
# https://numpy.org/doc/stable/user/basics.indexing.html#index-0

print(x_mat[[0,-1],:])

[[44 47 39 11 46]
 [37 48 34 42 15]]


**21.** [P] Now, show the first, third and fifth column of x_mat

In [76]:
# https://numpy.org/doc/stable/user/basics.indexing.html#index-0

print(x_mat[:,[0,2,4]])

[[44 39 46]
 [47 39 24]
 [37 19 23]
 [20 28 17]
 [49 39 43]
 [37 46 13]
 [15 21 27]
 [15 18 44]
 [15 22 26]
 [37 34 15]]


**22.** [P] Show the sum of each row.

In [77]:
# https://numpy.org/doc/stable/reference/routines.array-manipulation.html#basic-operations
# https://numpy.org/doc/stable/user/basics.indexing.html#index-0
# https://numpy.org/doc/stable/reference/generated/numpy.column_stack.html#numpy.column_stack

sums = np.sum(x_mat, axis=1)
print(np.column_stack((np.arange(0, x_mat.shape[0]), sums)))

[[  0 187]
 [  1 165]
 [  2 126]
 [  3 140]
 [  4 205]
 [  5 139]
 [  6 112]
 [  7 136]
 [  8 116]
 [  9 176]]
